general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # avoid having to press a key twice to wake the display.
}

listener {
    timeout = 300                              # 5min
    on-timeout = brightnessctl -s set 10       # dim backlight
    on-resume = brightnessctl -r                # restore backlight
}

listener {
    timeout = 330                              # 5.5min
    on-timeout = loginctl lock-session          # lock screen
}

listener {
    timeout = 360                              # 6min
    on-timeout = hyprctl dispatch dpms off      # screen off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1800                             # 30min
    on-timeout = systemctl suspend              # suspend
}
