#!/usr/bin/env bash
# scripts/gen-shell-inventory.sh -- regenerate scripts/shell-inventory.expected.
#
# core/, git/ and tools/ are the shell-agnostic modules .bashrc and .zshrc
# both source, so there is one floor, not one per shell -- see
# scripts/doctor.d/22-shell.sh.
#
# The bash/ and zsh/ adapters are deliberately excluded. They hold the surface
# that only one shell can have: bash/ is shopt/bind plus bash-completion
# (_gcmp/_rs/_rh, which zsh cannot load at all), zsh/ is the compdef
# equivalents. Names defined there are not part of a shared floor by
# definition, and asserting them would fail on whichever shell is not running.
#
# Sources core/git/tools in a clean, non-interactive, rc-file-free bash and
# prints every alias and function name that comes out the other side.
# Running without an rc file matters: this must reflect only what
# .shell_modules itself defines, not whatever else happens to live in the
# caller's ~/.bashrc. Aliases/functions gated behind `command -v <tool>`
# (bat, eza, agent, ...) won't appear unless that tool happens to be
# installed on the machine this runs on -- that's fine, doctor.d/22-shell.sh
# checks this list is a *subset* of the live inventory, not an exact match,
# so it stays valid across machines with different optional tools.
#
# Usage: scripts/gen-shell-inventory.sh > scripts/shell-inventory.expected
set -euo pipefail

root="$(git rev-parse --show-toplevel)"
modules="$root/bashrc/.shell_modules"

inventory="$(
    bash --norc -c '
        export DOTFILES="$1"
        for f in "$2"/core/*.sh "$2"/git/*.sh "$2"/tools/*.sh; do
            source "$f"
        done
        echo "===ALIASES==="
        compgen -a
        echo "===FUNCS==="
        compgen -A function
    ' _ "$root" "$modules"
)"

echo "# Generated by scripts/gen-shell-inventory.sh -- do not hand-edit."
echo "# Floor of unconditional alias/function names from core/, git/ and"
echo "# tools/ .shell_modules -- checked by scripts/doctor.d/22-shell.sh as"
echo "# a subset of the live inventory after sourcing .bashrc/.zshrc, so a"
echo "# module that silently fails to load shows up as a missing entry."
echo "# Regenerate after adding/removing an unconditional alias or"
echo "# function: scripts/gen-shell-inventory.sh > scripts/shell-inventory.expected"
printf '%s\n' "$inventory" | awk '
    /^===ALIASES===$/ { section = "alias"; next }
    /^===FUNCS===$/ { section = "func"; next }
    { print section, $0 }
' | sort -u
